namespace Assets.Scripts.Core.Tween
{
    public enum EaseType
    {
        Undefined = 0,
        Linear = 1,
        QuadOut = 2,
        QuadIn = 3,
        QuadInOut = 4,
        QuadOutIn = 5,
        ExpoOut = 6,
        ExpoIn = 7,
        ExpoInOut = 8,
        ExpoOutIn = 9,
        CubicOut = 10,
        CubicIn = 11,
        CubicInOut = 12,
        CubicOutIn = 13,
        QuartOut = 14,
        QuartIn = 15,
        QuartInOut = 16,
        QuartOutIn = 17,
        QuintOut = 18,
        QuintIn = 19,
        QuintInOut = 20,
        QuintOutIn = 21,
        CircOut = 22,
        CircIn = 23,
        CircInOut = 24,
        CircOutIn = 25,
        SineOut = 26,
        SineIn = 27,
        SineInOut = 28,
        SineOutIn = 29,
        ElasticOut = 30,
        ElasticIn = 31,
        ElasticInOut = 32,
        ElasticOutIn = 33,
        BounceOut = 34,
        BounceIn = 35,
        BounceInOut = 36,
        BounceOutIn = 37,
        BackOut = 38,
        BackIn = 39,
        BackInOut = 40,
        BackOutIn = 41,
        EndValue = 42
    }
}